# Generated by Django 5.2.12 on 2026-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_bio_alter_jobseekerprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
    ]
