# Generated by Django 5.2.12 on 2026-04-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_jobseekerprofile_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
    ]
