# Generated by Django 5.2.12 on 2026-04-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobseekerprofile_ai_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
