# Generated by Django 5.2.12 on 2026-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_phone_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='company_website',
            new_name='website',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
