# Generated by Django 5.2.12 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
