# Generated by Django 5.2.12 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_savedjob_ai_summary_savedjob_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
