# Generated by Django 5.2.12 on 2026-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_ai_summary_application_match_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='user',
        ),
    ]
